title: "Jahanara Suchi"
name: "Jahanara Suchi"
description: "PhD Applicant | Machine Learning | Artificial Intelligence"

author:
  author:
  avatar: "/images/profile.jpg.png"
  name: "Jahanara Suchi"
  bio: "PhD Applicant | Machine Learning | Explainable AI | Healthcare AI"
  location: "Dhaka, Bangladesh"
  employer: "American International University-Bangladesh (AIUB)"
  email: "jahanara.suchi41985@gmail.com"
  github: "jahanra02"
  linkedin: "jahanara-suchi-218b78208"
  googlescholar: ""
  orcid: ""
