title: "Jahanara Suchi"
name: "Jahanara Suchi"
description: "PhD Applicant | Computer Science & Engineering | AIUB"
url: "https://jahanra02.github.io"
baseurl: ""
repository: "jahanra02/jahanra02.github.io"

author:
  name: "Jahanara Suchi"
  bio: "CSE Graduate interested in Machine Learning & Explainable AI"
  location: "Dhaka, Bangladesh"
  employer: "AIUB"
  github: "jahanra02"
  linkedin: "jahanra02"

theme: "academicpages"
layout: "about"
